### ISSUE TITLE
Write certificate in cryptographic token

### ISSUE THREAD

**Issue by brennomarques** [MadLittleMods/node-usb-detection#114]
I would like an orientation if possible, I have a cryptographic USB Token brand SafeNet, store certificate, follow the link: [https: //www.google.com/search? Q = token + safenet & safe = off & sxsrf = ALeKk03Ay3mxXZY7VWx5Fx-CrX8ePJrWQA & 159407792418 & t isch & sa = X & ved = 2ahUKEwjYh6mD47nqAhVcEbkGHbtdBfoQ_AUoAXoECA0QAw & biw = 1920 & bih = 937 # imgrc = str6WOws33d62M.](url)
I am wanting to record a certificate inside that device I would like to know if with usb-detection meets? if you have any information or guidance on how I can accomplish this task.

**Comment by MadLittleMods** [comment]
@brennomarques You will have to try it yourself.

`usb-detection` doesn't read from your USB device. It just detects when USB devices are plugged in and taken out.

You will probably need to use a separate package like [`usb`](https://www.npmjs.com/package/usb) or maybe [`node-hid`](node-hid)
