### ISSUE TITLE
Was compiled against a different Node.js version using NODE_MODULE_VERSION 83. This version of Node.js requires NODE_MODULE_VERSION 80.

### ISSUE THREAD

**Issue by akanshSirohi** [MadLittleMods/node-usb-detection#119]
I have tried electron-rebuild but it gives me different kind of error.

**Comment by MadLittleMods** [comment]
@akanshSirohi See https://github.com/MadLittleMods/node-usb-detection#install-for-electron or these specific instructions: https://github.com/MadLittleMods/node-usb-detection/pull/118/files

**Comment by akanshSirohi** [comment]
Already Done! Still not working...
