### ISSUE TITLE
Can't install 1.1.0 on RapsberryPi2 B

### ISSUE THREAD

**Issue by guillaumewuip** [MadLittleMods/node-usb-detection#12]
Hi, I'm currently trying to use `usb-detection` on my RaspberryPi2 B with node `0.10.26` and npm `1.4.28`.

The command `npm install usb-detection` or `npm install usb-detection@1.1.0`  failed with [this error](http://pastebin.com/3TGC1310): http://pastebin.com/3TGC1310

Whereas `@1.0.0-1.0.3` install itself fine.

```
> usb-detection@1.0.3 preinstall /home/pi/panoPi/node_modules/usb-detection
> node-gyp rebuild

make: Entering directory '/home/pi/panoPi/node_modules/usb-detection/build'
  CXX(target) Release/obj.target/detection/src/detection.o
  CXX(target) Release/obj.target/detection/src/deviceList.o
  CXX(target) Release/obj.target/detection/src/detection_linux.o
  SOLINK_MODULE(target) Release/obj.target/detection.node
  SOLINK_MODULE(target) Release/obj.target/detection.node: Finished
  COPY Release/detection.node
make: Leaving directory '/home/pi/panoPi/node_modules/usb-detection/build'
usb-detection@1.0.3 node_modules/usb-detection
├── bindings@1.1.0
└── eventemitter2@0.4.14
```

Is node `0.10.36` no more supported ?

Thanks :)

**Comment by MadLittleMods** [comment]
@guillaumewuip We are now using [`nan`](https://www.npmjs.com/package/nan) to abstract node API layer. I am under the impression that those calls are compatible with "Node 0.8->0.12" as stated in the `nan` readme.

Just some notes, I haven't delved into this issue yet.

**Comment by guillaumewuip** [comment]
Ok thanks @MadLittleMods, I haven't really the knowledge to help debug this but feel free to ask me logs or anything.

**Comment by tommy7600** [comment]
Try to use gcc 4.8 and g++ 4.8

**Comment by tommy7600** [comment]
With some devices I get infinite loop with add and remove events. On windows and mac os everything is ok.

**Comment by apla** [comment]
I've added patch for node 0.10.x #26

**Comment by MadLittleMods** [comment]
@guillaumewuip Are things working for you now in 1.4.0 with @apla's change?

**Comment by guillaumewuip** [comment]
@MadLittleMods I'm sorry to not know. I don't even remember for which project I try to use `usb-detection`. I can't test it now, sorry :/
