### ISSUE TITLE
Get USB mount point

### ISSUE THREAD

**Issue by m0g** [MadLittleMods/node-usb-detection#18]
Hi,

quick question, on linux, is there a possibility to directly get the mount point of a usb device?

**Comment by MadLittleMods** [comment]
Hey @m0g,

I think the [`usb`](https://www.npmjs.com/package/usb) package will suit your needs, see https://github.com/MadLittleMods/node-usb-detection/issues/10

**Comment by m0g** [comment]
Ok,
thanks for your quick answer.

Since I'm using atom-shell/electron I have to wait for node-usb to update to Nan2.0 https://github.com/nonolith/node-usb/issues/89

**Comment by sudhakar3697** [comment]
A hack to get the mounted path
https://gist.github.com/sudhakar3697/e065128a7ca5694647aac7b94f481289
