### ISSUE TITLE
Get Path from Devices

### ISSUE THREAD

**Issue by jdnichollsc** [MadLittleMods/node-usb-detection#31]
Hi guys,

Is possible to get the path (file System) of each device? Any example about that?

Thanks in advance, Nicholls

**Comment by MadLittleMods** [comment]
> Related to:
> 
>  - https://github.com/MadLittleMods/node-usb-detection/issues/18
>  - https://github.com/MadLittleMods/node-usb-detection/issues/10
>
> https://github.com/MadLittleMods/node-usb-detection/issues/19

**Comment by MadLittleMods** [comment]
@jdnichollsc Do those references solve your use case?

Share your solution and close the issue accordingly

**Comment by jdnichollsc** [comment]
I don't understand :/

**Comment by MadLittleMods** [comment]
@jdnichollsc You gave a :+1: reaction to the reply with the references to other issues that tackle the same sort of problem. So I assume your figured out how to work something out. I was asking to share that solution you ended up with and if your issue is solved, close the issue.

**Comment by s-kashif** [comment]
Has anyone solved this issue yet?

**Comment by jdnichollsc** [comment]
@MadLittleMods my 👍 reaction is for your response, but these other issues are not related with my problem, what's the way to get the devicePath?
Thanks, Nicholls

**Comment by MadLittleMods** [comment]
@s-kashif @jdnichollsc There isn't a solution yet. the canonical issue for this is https://github.com/MadLittleMods/node-usb-detection/issues/19

**Comment by jdnichollsc** [comment]
ohh ok, thanks for your time 👍

**Comment by sudhakar3697** [comment]
A hack to get the mounted path
https://gist.github.com/sudhakar3697/e065128a7ca5694647aac7b94f481289
