### ISSUE TITLE
deviceName garbled in Windows

### ISSUE THREAD

**Issue by qqnp1100** [MadLittleMods/node-usb-detection#34]
Electron 1.4.5,
npm 4.0.2

log:
![image](https://cloud.githubusercontent.com/assets/14014255/20419859/3f79287c-ad94-11e6-867c-0347af31adbc.png)
and in macOS，the  devicename is true.

Who can tell me how to solve it?

**Comment by jyjunyz** [comment]
hi, has it been fixed yet？ I met the same problem

**Comment by MadLittleMods** [comment]
@jyjunyz If there isn't an update in the issue, then there isn't an update.

**Comment by MadLittleMods** [comment]
@marcong95 Can you provide the exact output from `usb-detection` for those devices? I'm curious what characters it is trying to use and mangling

**Comment by MadLittleMods** [comment]
@marcong95 If you're interested in submiting a PR, the relevant code is here,

 - https://github.com/MadLittleMods/node-usb-detection/blob/875c525cc55b8c8d161138e5055c6b40a15d0851/src/detection_win.cpp#L422-L432
 - https://github.com/MadLittleMods/node-usb-detection/blob/875c525cc55b8c8d161138e5055c6b40a15d0851/src/detection.cpp#L185-L186

**Comment by jyjunyz** [comment]
I resolved this, I will submit a PR later

**Comment by marcong95** [comment]
@MadLittleMods I don't know too much about C++ and its toolchain, but I will give a try. If @jyjunyz submitted his PR, just ignore mine.

**Comment by MadLittleMods** [comment]
The [fix](https://github.com/MadLittleMods/node-usb-detection/pull/86) is now shipped in [`usb-detection@4.4.0`](https://github.com/MadLittleMods/node-usb-detection/blob/master/CHANGELOG.md#440---2019-10-6) :tada: 

Thanks to @nononoone for the [fix](https://github.com/MadLittleMods/node-usb-detection/pull/86) ❤️
