### ISSUE TITLE
Possible to get usb port ?

### ISSUE THREAD

**Issue by dehlen** [MadLittleMods/node-usb-detection#4]
Hello,

i am using this library to detect whether my RFID Reader was plugged in or removed from the usb port. Unfortunately i also need the usb port of the plugged in device to retrieve a scanned card-id from my rfid scanner. I know there are several libraries out there where i can retrieve the scanned data from a hid device but to open this event i need the usb port the device is connected on. So any chance to get the port the device is plugged in on the monitor.on("add") event ?

I already saw that the plugged in device has a locationId but I am not sure how to use that to get the corresponding port.

Besides that i really love your lib. Great work !

King Regards,
David

**Comment by MadLittleMods** [comment]
@dehlen Did you end up finding a solution?

It seems like you wanted to find the serial port opened when the USB device is plugged in.

I would use [`serialport`](https://www.npmjs.com/package/serialport) and then get a list of ports available when the application starts. Then when any USB device is plugged in, check the current serial ports again and assume that the new ones came from the device. Not foolproof but should handle most situations.

**Comment by dehlen** [comment]
Yeah got it to work exactly like you described above. Sorry I totally forgot to come back and report my results.
