### ISSUE TITLE
Access Violation on Window 10

### ISSUE THREAD

**Issue by timfish** [MadLittleMods/node-usb-detection#44]
Thanks for this module!

In electron 1.7.8 I've recorded this access violation but have no idea how to reproduce it:

```
NotifyRemoved(ListResultItem_t *)
  detection.cpp:87
RtlpUnWaitCriticalSection
  ntdll.dll
```
I've got the full dump file if that'll help.

![image](https://user-images.githubusercontent.com/1150298/30799614-bc879c7a-a1dd-11e7-8276-5d591056fc3a.png)

**Comment by MadLittleMods** [comment]
@timfish It seems like you are past bundling `usb-detection` in your electron app but did you make sure to rebuild the package with electron, https://github.com/MadLittleMods/node-usb-detection/issues/39#issuecomment-315524803

I don't have any experience using this in Electron. If you can come up with some reproducible steps, I can check it out.

**Comment by timfish** [comment]
Yes, building and bundling is all setup. We use electron-builder which makes this all work with very little effort. The library is working well on Windows/Mac and Linux apart from this crash report I received. It can probably be ignored unless we start seeing a lot of occurrences!

**Comment by wujiazhong** [comment]
I met this crash issue that cannot access virtual address when building and bundling electron app with electron-packager on Windows 7 & 10. It works well on mac.
<img width="576" alt="image" src="https://user-images.githubusercontent.com/11980514/34068052-49c70c92-e270-11e7-9944-d253e0bf84e8.png">
