### ISSUE TITLE
Type Definitions

### ISSUE THREAD

**Issue by thegecko** [MadLittleMods/node-usb-detection#65]
Hiya,

I'd like to write some type definitions for `usb-detection`. Do you want a PR on the source code here or rather they were part of the [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped) project and published separately on npm?

**Comment by MadLittleMods** [comment]
@thegecko Feel free to submit a PR for adding a separate declaration file `index.d.ts`. I'm not familiar with using Typescript btw.

**Comment by thegecko** [comment]
PR created, was pretty simple in the end :)
