### ISSUE TITLE
USB-detection in Vue JS

### ISSUE THREAD

**Issue by CodebyOmar** [MadLittleMods/node-usb-detection#67]
I installed usb-detection in a vue js project but i'm getting this error when i compile my code using webpack 
warning  in ./node_modules/bindings/bindings.js
81:43-53 Critical dependency: the request of a dependency is an expression

**Comment by MadLittleMods** [comment]
@CodebyOmar As a note, you can't use `usb-detection` on the frontend in a browser. It also looks like a warning, not an error 🤷‍♂️ 

Related issue: https://github.com/MadLittleMods/node-usb-detection/issues/56

**Comment by MadLittleMods** [comment]
Closing as there hasn't been any response
