### ISSUE TITLE
How to get USB Intance ID?

### ISSUE THREAD

**Issue by hifong45** [MadLittleMods/node-usb-detection#68]
I found `instance-specific-ID` in `detection_win.cpp`, but can't get from `device["serialNumber"]`, it's `""`.

How to get it?

Thanks !

**Comment by MadLittleMods** [comment]
@hifong45 Not all devices have a serial number. See for example here, https://github.com/MadLittleMods/node-usb-detection/pull/62#pullrequestreview-123573550

**Comment by hifong45** [comment]
Excuse me, I want to get <instance-specific-ID>`: `5&376ABA2D&0&21’ in fact.
How can I do ?  I cant find the example or description
Thank you !!!!!

**Comment by hifong45** [comment]
Excuse me, I want to get instance-specific-ID : 5&376ABA2D&0&21’ in fact.
How can I do ? I cant find the example or description
Thank you !!!!!

**Comment by MadLittleMods** [comment]
@hifong45 If it's not appearing in the `serialNumber` property, then it might not be possible to get that information with this library yet.

You may have to correlate it with a device list from https://www.npmjs.com/package/usb or some other package.

**Comment by hifong45** [comment]
Ok, thank you!
