### ISSUE TITLE
Node 12 support

### ISSUE THREAD

**Issue by kryops** [MadLittleMods/node-usb-detection#80]
Hi there!

I tried upgrading my application to Node 12, and the following compile errors were thrown:

* `v8::Handle` does not exist any more
* `args[i]->NumberValue()` does not work any more

I don't really know C++, but I managed to get it working with the following changes:

https://github.com/kryops/node-usb-detection/commit/20ebc8bc2ade4319087d6476cf9f556c1c582b84

Could you please check if they make sense and don't break anything else (especially older versions of Node), and upgrade this package accordingly?

Thanks!

See also:
https://github.com/bcoin-org/bcrypto/issues/7
https://github.com/nodejs/node/issues/23122

**Comment by MadLittleMods** [comment]
@kryops Mind creating a pull request so we can add comments to the code itself that will be self contained in this project?
