### ISSUE TITLE
The same HID device, `node-hid` and `usb-detection` get different manufacturer data

### ISSUE THREAD

**Issue by orangeChu** [MadLittleMods/node-usb-detection#89]
This is the result of [node-hid](https://github.com/node-hid/node-hid):
![node-hid](https://user-images.githubusercontent.com/25950247/66287197-59137100-e907-11e9-80fd-b3ef87c5dbb1.png)

This is the result of [usb-detection](https://github.com/MadLittleMods/node-usb-detection):
![usb-detection](https://user-images.githubusercontent.com/25950247/66287215-67fa2380-e907-11e9-9b0c-3abd02c5f7cb.png)
(**note**: `manufacturer: "(标准系统设备)"` means `manufacturer: "(Standard USB Host Controller)"`)

**Comment by MadLittleMods** [comment]
I assume this is related to https://github.com/MadLittleMods/node-usb-detection/pull/86

cc @nononoone

**Comment by orangeChu** [comment]
Thanks @MadLittleMods .
I'm afraid it's not deviceName garbled problem.
This is the result of version 4.3.0:
![usb-detection@4 3 0](https://user-images.githubusercontent.com/25950247/66361898-2fb01f00-e9b3-11e9-9594-b1d144c065df.png)

It looks like `node-hid` and `usb-detection` take different values.

**Comment by nononoone** [comment]
> Thanks @MadLittleMods .
> I'm afraid it's not deviceName garbled problem.
> This is the result of version 4.3.0:
> ![usb-detection@4 3 0](https://user-images.githubusercontent.com/25950247/66361898-2fb01f00-e9b3-11e9-9594-b1d144c065df.png)
> 
> It looks like `node-hid` and `usb-detection` take different values.

It was fixed in version 4.4.0

**Comment by webees** [comment]
`HID`只是一种`USB`通信协议。

而`USB`有5种标准描述符：
设备描述符
配置描述符
字符描述符
接口描述符
端点描述符

`USB`描述符之间的关系是一层一层的。明显`node-usb-detection`与`node-hid`获取得描述符层次不同。

**Comment by orangeChu** [comment]
> `HID`只是一种`USB`通信协议。
> 
> 而`USB`有5种标准描述符：
> 设备描述符
> 配置描述符
> 字符描述符
> 接口描述符
> 端点描述符
> 
> `USB`描述符之间的关系是一层一层的。明显`node-usb-detection`与`node-hid`获取的描述符层次不同。你可以在windows设备管理器中查看，应该与`node-usb-detection`获取的信息一致。所以`node-usb-detection`没有毛病。另外，花钱购买vid和pid的可能有你想要的结果。
> 
> This is not a bug.

Thank you for your answer. :100:
